name: iOS 14

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Procursus
        run: |
          wget -q https://deimos.styres.me/bootstrap.tar.zst
          sudo gtar --preserve-permissions -xkf ./bootstrap.tar.zst -C /
          echo '/opt/procursus/bin' >> $GITHUB_PATH

      - name: Run PlainsTests
        run: xcodebuild CODE_SIGN_IDENTITY="" AD_HOC_CODE_SIGNING_ALLOWED=YES -project Plains.xcodeproj -scheme Plains -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst' test

      - name: Compress test results
        id: compress
        run: |
          COMPRESS_DATE=$(date +'%y%m%d-%H%M%S')
          echo "::set-output name=date::$COMPRESS_DATE"
          tar -czf Plains-${COMPRESS_DATE}.xcresult.tar.gz /Users/runner/Library/Developer/Xcode/DerivedData/Plains-*/Logs/Test/Test-Plains-*.xcresult

      - uses: actions/upload-artifact@v2.2.3
        with:
          name: test-results
          path: Plains- ${{ steps.compress.outputs.date }}.xcresult.tar.gz
