name: Catalina

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: procursus-cache
        with:
          path: ~/__cache
          key: ${{ runner.os }}-procursus

      - name: Setup Procursus Bootstrap (install)
        if: steps.procursus-cache.outputs.cache-hit != 'true'
        run: |
          wget https://apt.procurs.us/bootstrap_darwin-amd64.tar.zst
          sudo gtar --preserve-permissions -xkf ./bootstrap_darwin-amd64.tar.zst -C /
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH

      - name: Setup Procurus Bootstrap (cache)
        if: steps.procursus-cache.outputs.cache-hit == 'true'
        run: |
          sudo mkdir -p ~/__cache/procursus/var/cache/apt/archives/partial ~/__cache/procursus/var/lib/apt/lists/partial
          sudo rsync -aP ~/__cache/procursus /opt
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
        
      - name: Update Bootstrap
        run: |
          sudo apt update
          if [[ "${{ steps.procursus-cache.outputs.cache-hit }}" != true ]]; then
            sudo apt -V dist-upgrade -y || :
          fi
          sudo apt -V dist-upgrade -y

      - name: Copy Procursus to Cache Location
        run: |
          sudo mkdir -p ~/__cache
          sudo rsync -aP /opt/procursus ~/__cache
          sudo rm -rf ~/__cache/procursus/var/cache/apt/archives/partial ~/__cache/procursus/var/lib/apt/lists/partial ~/__cache/procursus/Library/dpkg/triggers/Lock
          
      - name: Setup Symlinks
        run: |
          sudo ln -s /Users/runner/Library/Caches/xyz.willy.Plains/plains.sources /opt/procursus/etc/apt/sources.list.d/plains.sources

      - name: Run PlainsTests
        id: tests
        run: set -o pipefail && xcodebuild CODE_SIGN_IDENTITY="" AD_HOC_CODE_SIGNING_ALLOWED=YES -project Plains.xcodeproj -scheme Plains -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst' test | xcpretty

      - name: Locate Test Results
        if: failure()
        id: results
        run: |
          cd /Users/runner/Library/Developer/Xcode/DerivedData/Plains-*/Logs/Test
          echo "::set-output name=path::$PWD"

      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Plains-Tests-Catalina.xcresult
          path: ${{ steps.results.outputs.path }}/*.xcresult
