name: Catalina

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Procursus
        run: |
          wget -q https://deimos.styres.me/bootstrap.tar.zst
          sudo gtar --preserve-permissions -xkf ./bootstrap.tar.zst -C /
          echo '/opt/procursus/bin' >> $GITHUB_PATH

      - name: Run PlainsTests
        run: xcodebuild CODE_SIGN_IDENTITY="" AD_HOC_CODE_SIGNING_ALLOWED=YES -project Plains.xcodeproj -scheme Plains -destination 'platform=macOS,arch=x86_64' test
